cache:
  directories:
    - $HOME/.composer/cache/files

language: php

env:
  global:
    - SYMFONY_VERSION=""
    - COMPOSER_OPTIONS="--prefer-stable"

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: COMPOSER_OPTIONS="--prefer-lowest --prefer-stable"
    - php: 7.2
    - php: 7.2
      env: SYMFONY_REQUIRE="4.4.*"
    - php: 7.3
      env: COVERAGE=yes SYMFONY_PHPUNIT_VERSION=7.5
    - php: 7.4
    - php: 8.0snapshot
      env: COMPOSER_OPTIONS=""

before_install:
  - if [ "$COVERAGE" != "yes" ]; then phpenv config-rm xdebug.ini; fi
  - composer global require --no-progress --no-scripts --no-plugins symfony/flex

install:
  - composer update $COMPOSER_OPTIONS
  - vendor/bin/simple-phpunit install

script:
  - if [ "$COVERAGE" = "yes" ]; then vendor/bin/simple-phpunit --coverage-clover=coverage.clover; else vendor/bin/simple-phpunit; fi
  - if [ "$COVERAGE" = "yes" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ "$COVERAGE" = "yes" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
